// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDds12FVZOKrn4QX4yWWMoXUhzlGa1pxeY',
    appId: '1:105360670411:web:db273abff4618f95a8654e',
    messagingSenderId: '105360670411',
    projectId: 'refuse-risk-app',
    authDomain: 'refuse-risk-app.firebaseapp.com',
    databaseURL: 'https://refuse-risk-app-default-rtdb.firebaseio.com',
    storageBucket: 'refuse-risk-app.appspot.com',
    measurementId: 'G-EKT7NEYBP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2S_t1xrTysNBPTMWskl1NHIt7HOCHmE4',
    appId: '1:105360670411:android:3d43ed36d7a2b6b5a8654e',
    messagingSenderId: '105360670411',
    projectId: 'refuse-risk-app',
    databaseURL: 'https://refuse-risk-app-default-rtdb.firebaseio.com',
    storageBucket: 'refuse-risk-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Ary-8pFiwjvyPfqa0FnLygPSQtgyuWo',
    appId: '1:105360670411:ios:2eb4e4a8ea2822f5a8654e',
    messagingSenderId: '105360670411',
    projectId: 'refuse-risk-app',
    databaseURL: 'https://refuse-risk-app-default-rtdb.firebaseio.com',
    storageBucket: 'refuse-risk-app.appspot.com',
    iosClientId: '105360670411-iua0kvregc1p1rah1dq34skgkihbjmfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationRefuseRisk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Ary-8pFiwjvyPfqa0FnLygPSQtgyuWo',
    appId: '1:105360670411:ios:9c942afdef0b2d7ca8654e',
    messagingSenderId: '105360670411',
    projectId: 'refuse-risk-app',
    databaseURL: 'https://refuse-risk-app-default-rtdb.firebaseio.com',
    storageBucket: 'refuse-risk-app.appspot.com',
    iosClientId: '105360670411-ckn75fmjqp42istinbuqk0895v5rbm3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.applicationRefuseRisk.RunnerTests',
  );
}
